[tool.poetry]
name = "cource-work-3"
version = "0.1.0"
description = ""
authors = ["vasya_k <vasya_kukarsev@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
